name: Run Unit Tests & SonarCloud Analysis

on:
  push:
    branches:
      - main # Hoặc tên branch chính của bạn (ví dụ: master, develop)
  pull_request:
    types: [opened, synchronize, reopened] # Chạy khi tạo hoặc cập nhật Pull Request

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Cần fetch toàn bộ lịch sử để SonarCloud có thể phân tích chính xác
          # đặc biệt là cho các tính năng "New Code" và "Branch Analysis".
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Sử dụng phiên bản Node.js phù hợp với dự án của bạn

      - name: Install dependencies
        run: |
          npm ci # 'npm ci' đảm bảo một bản cài đặt sạch và nhất quán trong môi trường CI
          # Nếu bạn dùng Yarn, hãy thay bằng yarn install --frozen-lockfile

      - name: Run Unit Tests with Coverage
        run: |
          # Chạy Jest với cờ --coverage để tạo báo cáo LCOV
          # và sử dụng jest-junit để tạo báo cáo JUnit (đã cấu hình trong jest.config.js)
          # --ci để báo hiệu Jest đang chạy trong môi trường CI
          # --reporters=default --reporters=jest-junit để đảm bảo cả console output và JUnit XML
          npm test -- --coverage --ci --reporters=default --reporters=jest-junit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          # GITHUB_TOKEN được cung cấp tự động bởi GitHub Actions, cần cho tính năng PR decoration
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SONAR_TOKEN là secret bạn đã cấu hình
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
