name: Run Unit Tests & SonarCloud Analysis (Yarn)

on:
  push:
    branches:
      - main # Hoặc tên branch chính của bạn (ví dụ: master, develop)
  pull_request:
    types: [opened, synchronize, reopened] # Chạy khi tạo hoặc cập nhật Pull Request

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Cần fetch toàn bộ lịch sử để SonarCloud phân tích chính xác

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Sử dụng phiên bản Node.js phù hợp với dự án của bạn
          cache: 'yarn' # Kích hoạt caching cho Yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile # Sử dụng yarn install với cờ --frozen-lockfile để cài đặt nhất quán
          # Đây là lệnh tương đương với 'npm ci'

      - name: Run Unit Tests with Coverage
        run: |
          # Chạy Jest với cờ --coverage để tạo báo cáo LCOV
          # và sử dụng jest-junit (đã cấu hình trong jest.config.js)
          # Yarn chạy các script trong package.json, không cần '--'
          yarn test --coverage --ci --reporters=default --reporters=jest-junit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # Sử dụng action chính thức của SonarSource
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Tự động cung cấp bởi GitHub Actions, cần cho PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Secret bạn đã cấu hình